controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_post:
    path: '/posts'
    controller: 'App\Controller\PostController::getPosts'
    methods: ['GET']

homepage:
    path: '/'
    controller: 'App\Controller\DefaultController::index'